### ISSUE TITLE
[Regression]: The notification is missing a friend's avatar

### ISSUE THREAD

**Issue by Monsterovich** [TokTok/qTox#208]
### Steps to reproduce

1. Hide qTox to the background
2. Receive message from a friend

### Observed Behavior

![notofication](https://github.com/user-attachments/assets/de44ba0a-c562-4ac1-9b21-4e169796ce4c)

### Expected Behavior

A friend's avatar or an avatar created based on a friend's public key

### Reproducibility

Always

### Operating System

Linux

### Operating System version/distro/name/etc.

Linux Mint

**Comment by iphydf** [comment]
Yeah that's kind of expected, we got rid of the snore-notify dependency and are now using It's built-in notify. We do pass it an icon, but I guess in some cases that doesn't work. We have plans to add a direct dbus call for notifications to make a better experience for Linux users.

**Comment by iphydf** [comment]
https://github.com/TokTok/qTox/commit/cfbd2bffa1b05709556fc60593c833ade95d6a57

Can you test qTox from before this commit? Maybe reverting this commit will work on master. See if that can give you an avatar in the notification.
