### ISSUE TITLE
[Bug]: error: ‘TOX_ERR_CONFERENCE_JOIN_NULL’ was not declared in this scope

### ISSUE THREAD

**Issue by lastrodamo** [TokTok/qTox#277]
### qTox Version

1.18.0-rc.2

### Toxcore Version

0.2.19

### Qt Version

6.7.3-r2

### Steps to reproduce

1. I compile qTox on gentoo

### Observed Behavior

FAILED: util/CMakeFiles/util_library.dir/src/toxcoreerrorparser.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DCMAKE_BUILD -DGIT_DESCRIBE=\"1.18.0_rc2\" -DGIT_DESCRIBE_EXACT=\"Nightly\" -DGIT_VERSION="\"build without git\"" -DLOG_TO_FILE=1 -DQTOX_PLATFORM_EXT -DQT_CORE_LIB -DQT_MESSAGELOGCONTEXT=1 -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_RESTRICTED_CAST_FROM_ASCII -I/var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2_build/util/util_library_autogen/include -I/var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2_build -I/var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2 -I/usr/include/libexif -I/usr/include/sqlcipher -I/usr/include/opus -I/usr/include/AL -I/var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2/util/include -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++  -march=native -O2 -pipe -fno-exceptions -fstack-protector-all -std=gnu++20 -fPIC -fno-common -fstrict-overflow -ftrapv -pedantic-errors -Wall -Wcast-align -Wdouble-promotion -Wextra -Wformat=2 -Wmissing-declarations -Wnon-virtual-dtor -Wnull-dereference -Wold-style-cast -Woverloaded-virtual -Wshadow -Wsign-compare -Wundef -Wduplicated-cond -Wlogical-op -Wdate-time -Wstack-protector -MD -MT util/CMakeFiles/util_library.dir/src/toxcoreerrorparser.cpp.o -MF util/CMakeFiles/util_library.dir/src/toxcoreerrorparser.cpp.o.d -o util/CMakeFiles/util_library.dir/src/toxcoreerrorparser.cpp.o -c /var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2/util/src/toxcoreerrorparser.cpp
/var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2/util/src/toxcoreerrorparser.cpp: In function ‘bool ToxcoreErrorParser::parseErr(Tox_Err_Conference_Join, const char*, int, const char*)’:
/var/tmp/portage/net-im/qtox-toktok-1.18.0_rc2/work/qTox-1.18.0-rc.2/util/src/toxcoreerrorparser.cpp:154:10: error: ‘TOX_ERR_CONFERENCE_JOIN_NULL’ was not declared in this scope; did you mean ‘TOX_ERR_CONFERENCE_JOIN_OK’?
  154 |     case TOX_ERR_CONFERENCE_JOIN_NULL:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          TOX_ERR_CONFERENCE_JOIN_OK
ninja: build stopped: subcommand failed.

### Expected Behavior

I need to compile on gentoo.

### Reproducibility

Always

### Operating System

Linux

### Operating System version/distro/name/etc.

Gentoo

**Comment by robinlinden** [comment]
qTox requires c-toxcore 0.2.20 right now.

`TOX_ERR_CONFERENCE_JOIN_NULL` was added in https://github.com/TokTok/c-toxcore/commit/9610ac31c5f00f24f137478819d67e3eda832bec which was first released in https://github.com/TokTok/c-toxcore/releases/tag/v0.2.20.

**Comment by iphydf** [comment]
Can you try this? https://github.com/TokTok/qTox/pull/280

**Comment by lastrodamo** [comment]
I upgrade my ebuild with the latest version of qtox and again I have the same error.

**Comment by iphydf** [comment]
I don't think it's possible that 0.2.20 has this issue. If you want to contribute a CI check to include a Gentoo build, I'm happy to make it work. In the meantime, can you check if current `master` has the same error or a slightly different one? Maybe another enum is missing?

**Comment by Chiitoo** [comment]
There is no 0.2.20 yet in the official Gentoo repository, but that should change very soon-like.

I wonder what happened with the minimum toxcore version check there, which should have bailed during configure.

**Comment by iphydf** [comment]
https://github.com/TokTok/dockerfiles/pull/198 - we'll reduce that requirement.

**Comment by Chiitoo** [comment]
Yeah, I suppose that works too.  :]

As for the version check, it seems that when it was moved around [1] a bit, it no longer has any effect here.

I did originally wonder if it should be in the 'pkg-config' block too, but, didn't really go looking how to test it.

1. https://github.com/TokTok/qTox/commit/de7c4909aac1d363638a626043358491d55b93ff
