### ISSUE TITLE
Unchangeable tiny font

### ISSUE THREAD

**Issue by Aranad** [TokTok/qTox#28]
##### Brief Description
The font size is too tiny to read, and changing it in settings does nothing. I've attached a screenshot so you can see the UI compared to title bar and normal menu text. As you can see I've tried setting the font size to the max 99px. The setting is retained even after restarting, but it has no effect.

OS: Linux (Debian Buster)  
qTox version: (1.17.2)  
Commit hash:  465d82606813439ee14425f7462903bb39f2da30
toxcore:  0.2.11
Qt:  5.7.1
…
![tox-small](https://user-images.githubusercontent.com/1755922/81347985-56813000-9111-11ea-8499-7911ce83f607.jpg)

**Comment by nurupo** [comment]
Wrong repository. qTox repo is at https://github.com/qTox/qTox.

**Comment by iphydf** [comment]
Please file the issue there. I'll disable issues on this repo afterwards.

**Comment by Aranad** [comment]
Oops sorry, ok issues filled in over there.
