### ISSUE TITLE
Default language is Arabic

### ISSUE THREAD

**Issue by blackPantherOS** [TokTok/qTox#3]
##### Brief Description
Linux - blackPanther OS
qTox version:  latest git
toxcore:  1.10
Qt: 5.6.2  

Default language is Arabic and user clicked to settings icon, switch to Arabic again

**Comment by zoff99** [comment]
@blackPantherOS 
qTox repo is at: https://github.com/qTox/qTox
or do you mean its a bug in toxcore?

**Comment by SkyzohKey** [comment]
Toxcore has not i18n integrations so it's a qTox issue and should be reported on the correct repository as specified by @zoff99, thus closing. :p
